# Generated by Django 5.1.7 on 2025-03-31 11:57

import myauth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myauth", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                null=True,
                upload_to=myauth.models.profile_preview_directory_path,
            ),
        ),
    ]
